### ISSUE TITLE
How to connect to microsoft bot which have a multiple knowledge base (i.e having a url)

### ISSUE THREAD

**Issue by cr33dx** [codeforequity-at/botium-box-basic-dist#11]
HI, this is my botium.json

``` JSON
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "Directline3 Plugin Sample",
      "CONTAINERMODE": "directline3",
      "DIRECTLINE3_DOMAIN": "https://directline.botframework.com/v3/directline/conversations/4GPLdDV44gA57qA5FUyePl-a/activities",
      "DIRECTLINE3_WEBSOCKET" : true,
      "DIRECTLINE3_SECRET":" bot-secret",
      "DIRECTLINE3_POLLINGINTERVAL": 1000,
      "DIRECTLINE3_BUTTON_TYPE": "message",
      "DIRECTLINE3_BUTTON_VALUE_FIELD": "text"
    }
  }
}
```

I'm trying to connect to my bot but im getting the following error
```CONSOLE
(node:7708) UnhandledPromiseRejectionWarning: Error: Error posting activity: Error: failed to connect
```
And how do i connect my same bot with botium-box

**Comment by codeforequity-at** [comment]
The DIRECTLINE3_DOMAIN capability should only be used when accessing a bot not (yet) connected to the Azure bot service.
I see no reason why you could not just use the directline secret without explicitly giving the domain url.

**Comment by cr33dx** [comment]
For a single bot secret there are multiple bots running.
It is like for every knowledge base there is a different bot running.
And how do i connect to bot i.e hosted locally.

**Comment by codeforequity-at** [comment]
Botium is using the DirectLineJS library (https://github.com/Microsoft/BotFramework-DirectLineJS), so if the scenario you describe is possible this library, than it is possible with Botium. But I am not skilled enough with Bot Framework to propose a solution. Can you point me to some docs describing your setup ?

Maybe the Botium LUIS connector would be an option for you.

**Comment by cr33dx** [comment]
I've to ask my organisation for docs relating to there set up in the meanwhile can you tell me how do I connect to my bot i.e running locally. currently, I can run the bot in bot emulator with app id and password.

**Comment by cr33dx** [comment]
I got a way around where I could get the direct line secret for a particular bot thankyou.

**Comment by codeforequity-at** [comment]
Just for the records, can you briefly describe what you did, maybe someone else will have similar troubles and can lookup how you solved it ...

**Comment by cr33dx** [comment]
Hi, sorry for not describing the steps taken.
I ran the bot locally and tunnelled it to my azure bot service account via ngrok where for every instance of bot a new directline secret is generated
