### ISSUE TITLE
Partial matching in Botium

### ISSUE THREAD

**Issue by dShreya1701** [codeforequity-at/botium-box-basic-dist#12]
I want o pass my test cases even if there is only 90% match in bot response and expected bot response. But botium only passes the test cases when there is 100% match. Is it possible to do partial matching in botium?

**Comment by codeforequity-at** [comment]
it is not possible to pass a test run if not 100% of the test cases are passed. without more information I cannot tell if your question makes sense.

**Comment by dShreya1701** [comment]
sometimes my bot is giving response with HTML tags in botium but while testing manually with bot the HTML tags are not coming.....so while testing with botium......expected response doesn't contain html tags and Bot response contains HTML tags.....and as a result the testcases are failing..........both the response are same the only difference is HTML tags.
for eg.
#me 
how many days are left?
#Bot 
only 10 days are left

but bot response is:
only <br>10</br> days are left

**Comment by codeforequity-at** [comment]
Well, Botium doesn't just invent HTML tags. Furthermore, for assertions Botium normalizes the text - it removes all html tags. What connector are you using ?

**Comment by dShreya1701** [comment]
Generic HTTP/JSON interface

**Comment by codeforequity-at** [comment]
Do you have a logfile of the agent ?
