### ISSUE TITLE
Getting html tags in botium as a bot response

### ISSUE THREAD

**Issue by dShreya1701** [codeforequity-at/botium-box-basic-dist#13]
I am getting HTML tags in bot response while testing in botium. But while testing bot manually I am not getting those HTML tags.It seems a problem with Botium.Any Suggestions?

Thanks in Advance.

**Comment by codeforequity-at** [comment]
Botium uses the "raw" responses from the chatbot. It's possible that the client you are using for manual testing is just removing those html tags on the fly.

**Comment by dShreya1701** [comment]
But then the testcases are failing as there is no partial matching in botium......and html tags are not in bot's response. Any solution for this?

**Comment by codeforequity-at** [comment]
See Issue #12
