### ISSUE TITLE
User being sent  as message when using excel sheet as test.

### ISSUE THREAD

**Issue by cr33dx** [codeforequity-at/botium-box-basic-dist#14]
So I'm using the default excel sheet provided by you. which has 2 columns named User and Bot but when running test User is being sent as a message to bot.
Attaching screenshot for the same.
![Screenshot (6)](https://user-images.githubusercontent.com/8844755/54182403-709c8f80-44c7-11e9-9777-00906ea16719.png)

And here is the screenshot of default excel.

![Screenshot (7)](https://user-images.githubusercontent.com/8844755/54182443-8dd15e00-44c7-11e9-8f53-1e4a8775bc21.png)

**Comment by codeforequity-at** [comment]
You have to adapt the field "Row number to start searching" to 2, so that the header line is omitted.
This should actually be "2" (which is the default since Botium Box 1.3):

![image](https://user-images.githubusercontent.com/26287439/54186106-e2b2ab80-44aa-11e9-8893-665de5a19704.png)

**Comment by cr33dx** [comment]
thanks. can I add this as a comment in 
[Botium Scripting](https://github.com/codeforequity-at/botium-core/wiki/Botium-Scripting)

**Comment by codeforequity-at** [comment]
There is a section about it (https://github.com/codeforequity-at/botium-core/wiki/Botium-Scripting#composing-in-excel-files), but maybe it's not marked as important as it may be ...
