### ISSUE TITLE
botium not taking buttons in convos

### ISSUE THREAD

**Issue by dShreya1701** [codeforequity-at/botium-box-basic-dist#15]
#me 
hi

#bot  
hi user,I can help you with following things:
1.order food
2.groceries
3.xyz

so here I am getting response from bot while testing in botium as:
hi user,I can help you with following things:

options are not coming in chats but while testing manually with the bot the options are coming as buttons. Any solution for this?

**Comment by codeforequity-at** [comment]
You have to configure the json-path for Botium to find the buttons in the JSON-Response:

https://github.com/codeforequity-at/botium-core/wiki/operation-mode-simplerest#simplerest_buttons_jsonpath
