### ISSUE TITLE
Bot answers in Live chat are shown before question

### ISSUE THREAD

**Issue by oferdan** [codeforequity-at/botium-box-basic-dist#18]
When I'm Live chatting with bot, bot answers are shown before my questions. Conversation starts empty, I write "Hi Bot" in console, bot reply is shown first above my question. Please see attachement. 

![Screenshot_2019-05-16 Live Chat with I am Botium Botium Box](https://user-images.githubusercontent.com/11064555/57847990-1a561080-77d8-11e9-9999-57cb7d46fdfb.png)

**Comment by codeforequity-at** [comment]
Known bug, already fixed, part of the next build.
