### ISSUE TITLE
Can't choose Other for Webdriver Script on Quickstart page

### ISSUE THREAD

**Issue by oferdan** [codeforequity-at/botium-box-basic-dist#19]
Can't choose "Other (Specify Selenium Selectors)" for Webdriver Script on Quickstart page, although I can choose it on Chatbots page. Please see attachments.

![Screenshot_2019-05-16 Quickstart Botium Box](https://user-images.githubusercontent.com/11064555/57848436-2f7f6f00-77d9-11e9-9c1b-6939bf5f038d.png)

![Screenshot_2019-05-16 Chatbot Botium Box](https://user-images.githubusercontent.com/11064555/57848443-34442300-77d9-11e9-801a-7db940f907b2.png)

**Comment by codeforequity-at** [comment]
Works as designed. Quick start is for most simple configurations, Webdriver with Selenium selectors is out of scope for a "Quickstart" project.
