### ISSUE TITLE
Where my test data gets saved

### ISSUE THREAD

**Issue by hitesh22nov** [codeforequity-at/botium-box-basic-dist#2]
Hi,

I am facing issues with storage of my test projects/chatbots/data created in botium box community edition.
Sometimes the data gets wiped out and botium box gets up with only default data in it. I have installed on my server.
Please tell me the way to save my data.

Thanks in advance

**Comment by codeforequity-at** [comment]
hi, Botium uses Prisma as a storage backend, which itself uses Mysql or Postgresql, depending on the configuration. You should keep your Prisma service running and not tear it down (for example by doing a "docker-compose down" to remove the containers).

**Comment by codeforequity-at** [comment]
But there are other setups possible without docker containers. you will need some prisma know-how to set it up with an existing mysql or postgresql instance, for example. But Botium doesn't care what storage backend prisma is configured to use.

**Comment by codeforequity-at** [comment]
The default docker-compose for Botium will use a docker volume for mysql storage, so the data will not vanish when you tear down the container. But of course, when using it in production you should establish your own management and admin strategy for Prisma and Redis.
