### ISSUE TITLE
Botium Box-Community edition Blocker in Virtual machine

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-box-basic-dist#20]
Hi 
In  one of our Banking application which is highly secured and had installed Botium Box in VM.
The server is getting blocked and 127.0.0.1:4000 not Loading(Browser) .Hence need to understand in **docker-compose-all.yml**.It uses Redis, prism and many ports as i have to raise to my IT Team to whiteList the URL's and ports consumed in docker-compose.yml file .

Please suggest List of URL's and ports to be whiteListed .Hence forth we can successfully connect to all ports and URL.

**Comment by codeforequity-at** [comment]
very good point, i will add this to the documentation
for enterprise, there is documentation available
https://botium.atlassian.net/wiki/x/bIAH

in short: opening port 4000 is sufficient for single server installations.
you can map it to port 80 if you want, the default http port.




Vijaysimha <notifications@github.com> schrieb am Mo., 10. Juni 2019, 18:13:
