### ISSUE TITLE
BotiumBox community edition -Docker container fails

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-box-basic-dist#21]
How to resolve failure for creating **botiumbox_web** **fails** .
**Workaround** :
1.Computer management->Local users and Groups->Users->Create new user->DockerHost ->added Administrator and Users.
2.Groups->docker-users ->Added DockerHost which is created under Users.
This approach didnt resolved the problem.Please help me in guiding the below error:

Creating botiumbox_web_1 ... error
ERROR: for botiumbox_web_1  Cannot create container for service web: b'Drive sharing failed for an unknown reason'

![image](https://user-images.githubusercontent.com/30192609/59564504-55609380-9065-11e9-8761-34bf035a1060.png)

**Comment by codeforequity-at** [comment]
Please try to create the directory testsets and botiumwork in the working directory, maybe this helps.

**Comment by codeforequity-at** [comment]
news ?
