### ISSUE TITLE
Can´t use the Pause logic hook with Dialogflow.

### ISSUE THREAD

**Issue by fuchini** [codeforequity-at/botium-box-basic-dist#24]
When I try to insert a pause I get an "Input text not set" error

**Comment by codeforequity-at** [comment]
pls show your convo file

**Comment by fuchini** [comment]
I'm using excel files and this one works without a problem:

![Bot1](https://user-images.githubusercontent.com/1280039/62155479-9982bd00-b2ce-11e9-9da0-9ff100348256.PNG)

This doesn´t:

![Bot2](https://user-images.githubusercontent.com/1280039/62155515-b9b27c00-b2ce-11e9-9206-b9fd712d1c16.PNG)

**Comment by codeforequity-at** [comment]
You should place the PAUSE 300 in the same cell as the USER_WELCOME_UTT, so that Botium knows that those two instructions should be combined.
This will be fixed with the next build - obviously, the current way, to combine multiple statements into one Excel cell, is a source of confusion.

**Comment by fuchini** [comment]
Hi, thanks, I'm trying to do it this way:

![snap](https://user-images.githubusercontent.com/1280039/62376412-2d8a9980-b506-11e9-94f9-a8b937c82e8c.PNG)

I'm trying to place it in the same cell but I'm getting:

`PauseLogicHook Wrong argument. It must be integer "100 USER_WELCOME_UTT" at exports pause`

**Comment by codeforequity-at** [comment]
pls add a line break after the PAUSE 100 instruction

**Comment by fuchini** [comment]
Thanks! That was it!
