### ISSUE TITLE
"Deploy to Heroku" Button fails to build, ELIFECYCLE Error in building nodegit@0.24.3

### ISSUE THREAD

**Issue by Dangeranger** [codeforequity-at/botium-box-basic-dist#25]
Hello 👋 ,

Thank you for making this project open source. 

While attempting to use the "Deploy to Heroku" button within the README.md and configuring the environment variables with values from the RedisLabs and Prisma services created prior to starting, the Heroku build process fails when attempting to build `nodegit@0.24.3`.

Please see the output of the server logs during the build, linked to in the following Gist:
https://gist.github.com/Dangeranger/1c4911692453a37dab00d7c270dd11a0

The building of the project using Docker and Docker-Compose on a local development machine proceeded successfully on MacOS and Windows using `Docker version 19.03.1, build 74b1e89`.

It appears that Heroku is attempting to run the following scripts within the Docker image https://hub.docker.com/r/heroku/nodejs/dockerfile which differs from the Docker images within the project significantly in regards to installed build tools. 

  - `npm run prepare:agent`
  - `npm run prepare:server`

Maybe the reason that `nodegit@0.24.3` cannot be built is due to those differences?

Please let me know if there is additional information that you can provide about deploying Botium to Heroku, or if you need more details from me about the errors observed.
🙇

**Comment by codeforequity-at** [comment]
hi, we are about to cancel the "deploy to heroku" feature because heroku cannot fulfill all prerequisites for botium box anymore. easiest way to run is with docker-compose
