### ISSUE TITLE
Unable to select the "Git Repository" for test sets

### ISSUE THREAD

**Issue by mickkasisto** [codeforequity-at/botium-box-basic-dist#3]
Referring to this article:
https://medium.com/@floriantreml/botium-in-a-nutshell-part-5-the-botium-box-a4f44d4c96b0
***The Test Set Library and Humanification
Test case files are managed in test set libraries. Within a single test set, you can combine test cases from various sources:
Write Convos and Utterances in Botium Box
Upload Excel files
Register a shared folder holding the test cases
Register a Git repository holding the test cases
Note: in real-life scenarios, the last option (Git repository) is clearly the best option as it allows the test cases to be under version control.

Unable to select the Git Repository button to enable us to put our botium tests under source control.
Is there a work around for this?

Thanks in adavance

**Comment by codeforequity-at** [comment]
Using git repositories is not available in community edition. Using shared folders is possible.
