### ISSUE TITLE
Deploy to Azure license issue

### ISSUE THREAD

**Issue by omoravskyi** [codeforequity-at/botium-box-basic-dist#37]
I'm using [this tutorial](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/26411032/Installation+Step+for+the+Azure+Cloud) to deploy **botium-box-basic-dist** to Azure. 
Everything went normal and application was deployed successfully, but the _license.key_ file I added to _resources_ folder was not applied. So I see **FinishRegistration** page all the time:
![image](https://user-images.githubusercontent.com/60383994/75660652-a4db0400-5c74-11ea-9bb5-2cca7f62d466.png)

However when running application locally the key is in fact applied and everything is alright.
Can you give me any advises on what could go wrong? 
Thanks in advance!

**P.S.** To make docker-compose.yml working for Azure I had to make relative paths for volumes use variable ${WEBAPP_STORAGE_HOME}, like this:
./testsets:/app/server/testsets -> ${WEBAPP_STORAGE_HOME}/testsets:/app/server/testsets
This is Azure requirement so it make sense to add this point to tutorial.

**Comment by omoravskyi** [comment]
I understood what I did wrong - you have to add **LICENSE_KEY** environment variable to _docker-compose.yml_ and set it to your license.key. I discovered it by going through [tutorial for Enterprise edition](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/27230209/Installation+as+Azure+Multi-Container+App).

Would be nice to include this info in tutorial for Community Edition.

However now I can't log in as default **Usernames** and **Password** are not working. What could be the reason of this?

**Comment by codeforequity-at** [comment]
Thanks for the hints, I updated the Wiki doc with this information.

Regarding your problem with username and password, the only problem I can think of is that the database seed process wasn't successful (but in this case it shouldn't launch at all).

Can you try to get a look at the log files, maybe you find some hint there.
https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-multi-container-app#find-docker-container-logs

**Comment by omoravskyi** [comment]
Thanks for the quick response.

I actually used your advice from the updated tutorial and created Azure database separately from the App service. After that logging in went successful.
