### ISSUE TITLE
Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5001ms.

### ISSUE THREAD

**Issue by ShivamGarg2910** [codeforequity-at/botium-box-basic-dist#38]
I installed Botium Box in my linux VM, got all the latest images for dependencies and configured the docker-compose.yml.
On running command: docker-compose up -d, container is being created. When I try docker ps -a, it displays instances running. But when I see logs, it displays error in MySQL connection.
![image](https://user-images.githubusercontent.com/25713041/75986229-b130bc80-5f13-11ea-88c7-80b590320198.png)
![image](https://user-images.githubusercontent.com/25713041/75986280-cc033100-5f13-11ea-8a6e-5a1e46e11e3c.png)

I even tried adding a command in docker-compose.yml file for changing the default authentication method. But no success.

**Comment by codeforequity-at** [comment]
Botium Box tested with mysql 5.7, not with the latest version 8. My suggestion is to go back to the version 5.7 as in the docker-compose.yml file.

But from my knowledge, using

    command: --default-authentication-plugin=mysql_native_password_

in docker-compose should also work - not tested, just read about it. Is this the command you used ?

**Comment by ShivamGarg2910** [comment]
Yes, I used this command.

**Comment by ShivamGarg2910** [comment]
The error is solved, the problem was there because of mysql image/mysql configuration.
I deleted the mysql folder in my current directory and restarted the container.
Worked fine afterwards.
Thanks for the help.
