### ISSUE TITLE
this.context.IsUserInputValid is not a function

### ISSUE THREAD

**Issue by veralimita** [codeforequity-at/botium-box-basic-dist#5]
Trying to add new test case using convo file but getting "this.context.IsUserInputValid is not a function" error. 
**Version**: 1.1.2

**Comment by codeforequity-at** [comment]
looking into this ...

**Comment by codeforequity-at** [comment]
Please use Version 1.1.3 (just published).

**Comment by veralimita** [comment]
@codeforequity-at thank you so much.
