### ISSUE TITLE
 testcase failed when getting variable output from bot using botium box

### ISSUE THREAD

**Issue by dShreya1701** [codeforequity-at/botium-box-basic-dist#7]
I am using botium-box I have the following convo file:

#me
hi bot

#bot
hi,what can I do for you?

#me
what is the date today?

#bot
It's 11th february 2019.

Here the date is a variable and changes everyday so I have to change it everyday in convo file otherwise the testcase is failing.

I have tried few solutions:

1. setting SCRIPTING_ENABLE_MEMORY to true in advance settings and using placeholder for variables. For eg.

#me
hi bot

#bot
hi,what can I do for you?

#me
what is the date today?

#bot
It's $Date.

2. I tried setting INTENT_CONFIDENCE to 70 in advance settings and using in convo file. For eg:
 
#me
hi bot

#bot
hi,what can I do for you?

#me
what is the date today?

#bot
INTENT_CONFIDENCE 
It's $Date.

3.I tried INTENT_CONFIDENCE directly in convo file without setting it in advance capabilities. For eg.

#me
hi bot

#bot
hi,what can I do for you?

#me
what is the date today?

#bot
INTENT_CONFIDENCE 70
It's $Date.

4. I tried using %s in place of variable. For eg. 

#me
hi bot

#bot
hi,what can I do for you?

#me
what is the date today?

#bot
It's %s.

Testcases are still failing.Is it a bug? Do I have to change any Botium settings?How can I do partial matching of responses?

**Comment by codeforequity-at** [comment]
Handled on Stackoverflow
https://stackoverflow.com/questions/54630859/testcase-failed-when-getting-variable-output-from-bot-using-botium-box/54631195#54631195
