### ISSUE TITLE
Facing an issue when i was trying to view the deployed app

### ISSUE THREAD

**Issue by krishnasaikumarraju** [codeforequity-at/botium-box-basic-dist#9]
this is the screen i got:
![screenshot from 2019-02-20 20-57-26](https://user-images.githubusercontent.com/42143138/53102865-8c5ce780-3552-11e9-9a15-d2d39d24fe9c.png)
Command I tried : **heroku logs**
![screenshot from 2019-02-20 20-59-41](https://user-images.githubusercontent.com/42143138/53103061-e362bc80-3552-11e9-819b-19460946a92d.png)

Expectations:
I was trying a lot to work out on botium box to setup reports for alexa skill using smapi process, Can you please refer me a proper documentation to work and produce a possible output.

**Comment by codeforequity-at** [comment]
Information about Heroku logging is available [here](https://devcenter.heroku.com/articles/logging), for example - but this is the wrong forum to ask this question.

Obviously, Botium Box crashes - what Heroku version are you using ? As noted on the front page: 
_Attention: the Heroku free tier is not suitable for Botium Box production usage_ 

Botium Box has been designed for enterprise usage and scales very well up to multi-host enterprise deployments, but it has rather high base system requirements
